### PR TITLE
Update check for android or avdmanager

### PR DESCRIPTION
**Pull request by vchimev**

### CODE REVIEW

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by karel1980** [comment]
TIL: ${foo,,} is for case substitution, lowercasing the value of ${foo}. Bash on OSX doesn't have this. Had to look into a linux instance

**Comment by vchimev** [comment]
Hey @karel1980,

Yes, these scripts are obsolete and not in use anymore.

Currently, we use the following scripts in our CI:
https://gist.github.com/vchimev/f134c90aa4d68287c8c0e64d8b901214
https://gist.github.com/vchimev/969b0c495ac3c259eccc77445edb7852

**Comment by karel1980** [comment]
The scripts are still referenced from the documentation:
https://github.com/NativeScript/functional-tests-core/blob/master/docs/setup.md
Perhaps it's better to include the updated scripts in this repository?

**Comment by karel1980** [comment]
I don't mind creating the PR. Just let me know

**Comment by vchimev** [comment]
@karel1980, go ahead - that would be great! :)

**Pull request merged**
